#############################################################################
# Makefile for building: qgtkbridge
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  qgtkbridge.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile qgtkbridge.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -pthread -g -DQT_NO_KEYWORDS -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../../cef/chromium/src/cef -I/usr/include/gtk-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/home/kuscsik/cef/chromium/src/out/Debug/lib -lcef /home/kuscsik/cef/chromium/src/out/Debug/obj/cef/libcef_dll_wrapper.a -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype -lQt5Widgets -L/usr/lib/x86_64-linux-gnu -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		QtCefWidget.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		QtCefWidget.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qgtkbridge.pro \
		qgtkbridge.pro
QMAKE_TARGET  = qgtkbridge
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qgtkbridge


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qgtkbridge.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qgtkbridge.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile qgtkbridge.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qgtkbridge.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qgtkbridge.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/qgtkbridge1.0.0 || mkdir -p .tmp/qgtkbridge1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qgtkbridge1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/qgtkbridge1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp QtCefWidget.cpp .tmp/qgtkbridge1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/qgtkbridge1.0.0/ && (cd `dirname .tmp/qgtkbridge1.0.0` && $(TAR) qgtkbridge1.0.0.tar qgtkbridge1.0.0 && $(COMPRESS) qgtkbridge1.0.0.tar) && $(MOVE) `dirname .tmp/qgtkbridge1.0.0`/qgtkbridge1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qgtkbridge1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QPushButton \
		/usr/include/qt5/QtWidgets/qpushbutton.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QLayout \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/gtk-2.0/gtk/gtk.h \
		/usr/include/gtk-2.0/gdk/gdk.h \
		/usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h \
		/usr/include/glib-2.0/gio/gio.h \
		/usr/include/glib-2.0/gio/giotypes.h \
		/usr/include/glib-2.0/gio/gioenums.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/glib-2.0/gio/gaction.h \
		/usr/include/glib-2.0/gio/gactiongroup.h \
		/usr/include/glib-2.0/gio/gactiongroupexporter.h \
		/usr/include/glib-2.0/gio/gactionmap.h \
		/usr/include/glib-2.0/gio/gappinfo.h \
		/usr/include/glib-2.0/gio/gapplication.h \
		/usr/include/glib-2.0/gio/gapplicationcommandline.h \
		/usr/include/glib-2.0/gio/gasyncinitable.h \
		/usr/include/glib-2.0/gio/ginitable.h \
		/usr/include/glib-2.0/gio/gasyncresult.h \
		/usr/include/glib-2.0/gio/gbufferedinputstream.h \
		/usr/include/glib-2.0/gio/gfilterinputstream.h \
		/usr/include/glib-2.0/gio/ginputstream.h \
		/usr/include/glib-2.0/gio/gbufferedoutputstream.h \
		/usr/include/glib-2.0/gio/gfilteroutputstream.h \
		/usr/include/glib-2.0/gio/goutputstream.h \
		/usr/include/glib-2.0/gio/gbytesicon.h \
		/usr/include/glib-2.0/gio/gcancellable.h \
		/usr/include/glib-2.0/gio/gcharsetconverter.h \
		/usr/include/glib-2.0/gio/gconverter.h \
		/usr/include/glib-2.0/gio/gcontenttype.h \
		/usr/include/glib-2.0/gio/gconverterinputstream.h \
		/usr/include/glib-2.0/gio/gconverteroutputstream.h \
		/usr/include/glib-2.0/gio/gcredentials.h \
		/usr/include/glib-2.0/gio/gdatainputstream.h \
		/usr/include/glib-2.0/gio/gdataoutputstream.h \
		/usr/include/glib-2.0/gio/gdbusaddress.h \
		/usr/include/glib-2.0/gio/gdbusauthobserver.h \
		/usr/include/glib-2.0/gio/gdbusconnection.h \
		/usr/include/glib-2.0/gio/gdbuserror.h \
		/usr/include/glib-2.0/gio/gdbusintrospection.h \
		/usr/include/glib-2.0/gio/gdbusmessage.h \
		/usr/include/glib-2.0/gio/gdbusmethodinvocation.h \
		/usr/include/glib-2.0/gio/gdbusnameowning.h \
		/usr/include/glib-2.0/gio/gdbusnamewatching.h \
		/usr/include/glib-2.0/gio/gdbusproxy.h \
		/usr/include/glib-2.0/gio/gdbusserver.h \
		/usr/include/glib-2.0/gio/gdbusutils.h \
		/usr/include/glib-2.0/gio/gdrive.h \
		/usr/include/glib-2.0/gio/gemblemedicon.h \
		/usr/include/glib-2.0/gio/gicon.h \
		/usr/include/glib-2.0/gio/gemblem.h \
		/usr/include/glib-2.0/gio/gfileattribute.h \
		/usr/include/glib-2.0/gio/gfileenumerator.h \
		/usr/include/glib-2.0/gio/gfile.h \
		/usr/include/glib-2.0/gio/gfileicon.h \
		/usr/include/glib-2.0/gio/gfileinfo.h \
		/usr/include/glib-2.0/gio/gfileinputstream.h \
		/usr/include/glib-2.0/gio/gfileiostream.h \
		/usr/include/glib-2.0/gio/giostream.h \
		/usr/include/glib-2.0/gio/gioerror.h \
		/usr/include/glib-2.0/gio/gfilemonitor.h \
		/usr/include/glib-2.0/gio/gfilenamecompleter.h \
		/usr/include/glib-2.0/gio/gfileoutputstream.h \
		/usr/include/glib-2.0/gio/ginetaddress.h \
		/usr/include/glib-2.0/gio/ginetaddressmask.h \
		/usr/include/glib-2.0/gio/ginetsocketaddress.h \
		/usr/include/glib-2.0/gio/gsocketaddress.h \
		/usr/include/glib-2.0/gio/gioenumtypes.h \
		/usr/include/glib-2.0/gio/giomodule.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/glib-2.0/gio/gioscheduler.h \
		/usr/include/glib-2.0/gio/gloadableicon.h \
		/usr/include/glib-2.0/gio/gmemoryinputstream.h \
		/usr/include/glib-2.0/gio/gmemoryoutputstream.h \
		/usr/include/glib-2.0/gio/gmount.h \
		/usr/include/glib-2.0/gio/gmountoperation.h \
		/usr/include/glib-2.0/gio/gnativevolumemonitor.h \
		/usr/include/glib-2.0/gio/gvolumemonitor.h \
		/usr/include/glib-2.0/gio/gnetworkaddress.h \
		/usr/include/glib-2.0/gio/gnetworkmonitor.h \
		/usr/include/glib-2.0/gio/gnetworkservice.h \
		/usr/include/glib-2.0/gio/gpermission.h \
		/usr/include/glib-2.0/gio/gpollableinputstream.h \
		/usr/include/glib-2.0/gio/gpollableoutputstream.h \
		/usr/include/glib-2.0/gio/gpollableutils.h \
		/usr/include/glib-2.0/gio/gpropertyaction.h \
		/usr/include/glib-2.0/gio/gproxy.h \
		/usr/include/glib-2.0/gio/gproxyaddress.h \
		/usr/include/glib-2.0/gio/gproxyaddressenumerator.h \
		/usr/include/glib-2.0/gio/gsocketaddressenumerator.h \
		/usr/include/glib-2.0/gio/gproxyresolver.h \
		/usr/include/glib-2.0/gio/gresolver.h \
		/usr/include/glib-2.0/gio/gresource.h \
		/usr/include/glib-2.0/gio/gseekable.h \
		/usr/include/glib-2.0/gio/gsettingsschema.h \
		/usr/include/glib-2.0/gio/gsettings.h \
		/usr/include/glib-2.0/gio/gsimpleaction.h \
		/usr/include/glib-2.0/gio/gsimpleactiongroup.h \
		/usr/include/glib-2.0/gio/gsimpleasyncresult.h \
		/usr/include/glib-2.0/gio/gsimplepermission.h \
		/usr/include/glib-2.0/gio/gsocketclient.h \
		/usr/include/glib-2.0/gio/gsocketconnectable.h \
		/usr/include/glib-2.0/gio/gsocketconnection.h \
		/usr/include/glib-2.0/gio/gsocket.h \
		/usr/include/glib-2.0/gio/gsocketcontrolmessage.h \
		/usr/include/glib-2.0/gio/gsocketlistener.h \
		/usr/include/glib-2.0/gio/gsocketservice.h \
		/usr/include/glib-2.0/gio/gsrvtarget.h \
		/usr/include/glib-2.0/gio/gsimpleproxyresolver.h \
		/usr/include/glib-2.0/gio/gtask.h \
		/usr/include/glib-2.0/gio/gsubprocess.h \
		/usr/include/glib-2.0/gio/gsubprocesslauncher.h \
		/usr/include/glib-2.0/gio/gtcpconnection.h \
		/usr/include/glib-2.0/gio/gtcpwrapperconnection.h \
		/usr/include/glib-2.0/gio/gtestdbus.h \
		/usr/include/glib-2.0/gio/gthemedicon.h \
		/usr/include/glib-2.0/gio/gthreadedsocketservice.h \
		/usr/include/glib-2.0/gio/gtlsbackend.h \
		/usr/include/glib-2.0/gio/gtlscertificate.h \
		/usr/include/glib-2.0/gio/gtlsclientconnection.h \
		/usr/include/glib-2.0/gio/gtlsconnection.h \
		/usr/include/glib-2.0/gio/gtlsdatabase.h \
		/usr/include/glib-2.0/gio/gtlsfiledatabase.h \
		/usr/include/glib-2.0/gio/gtlsinteraction.h \
		/usr/include/glib-2.0/gio/gtlsserverconnection.h \
		/usr/include/glib-2.0/gio/gtlspassword.h \
		/usr/include/glib-2.0/gio/gvfs.h \
		/usr/include/glib-2.0/gio/gvolume.h \
		/usr/include/glib-2.0/gio/gzlibcompressor.h \
		/usr/include/glib-2.0/gio/gzlibdecompressor.h \
		/usr/include/glib-2.0/gio/gdbusinterface.h \
		/usr/include/glib-2.0/gio/gdbusinterfaceskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobject.h \
		/usr/include/glib-2.0/gio/gdbusobjectskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobjectproxy.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanager.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerclient.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerserver.h \
		/usr/include/glib-2.0/gio/gdbusactiongroup.h \
		/usr/include/glib-2.0/gio/gremoteactiongroup.h \
		/usr/include/glib-2.0/gio/gmenumodel.h \
		/usr/include/glib-2.0/gio/gmenu.h \
		/usr/include/glib-2.0/gio/gmenuexporter.h \
		/usr/include/glib-2.0/gio/gdbusmenumodel.h \
		/usr/include/glib-2.0/gio/gnotification.h \
		/usr/include/gtk-2.0/gdk/gdkscreen.h \
		/usr/include/cairo/cairo.h \
		/usr/include/cairo/cairo-version.h \
		/usr/include/cairo/cairo-features.h \
		/usr/include/cairo/cairo-deprecated.h \
		/usr/include/gtk-2.0/gdk/gdktypes.h \
		/usr/include/pango-1.0/pango/pango.h \
		/usr/include/pango-1.0/pango/pango-attributes.h \
		/usr/include/pango-1.0/pango/pango-font.h \
		/usr/include/pango-1.0/pango/pango-coverage.h \
		/usr/include/pango-1.0/pango/pango-types.h \
		/usr/include/pango-1.0/pango/pango-gravity.h \
		/usr/include/pango-1.0/pango/pango-matrix.h \
		/usr/include/pango-1.0/pango/pango-script.h \
		/usr/include/pango-1.0/pango/pango-language.h \
		/usr/include/pango-1.0/pango/pango-bidi-type.h \
		/usr/include/pango-1.0/pango/pango-break.h \
		/usr/include/pango-1.0/pango/pango-item.h \
		/usr/include/pango-1.0/pango/pango-context.h \
		/usr/include/pango-1.0/pango/pango-fontmap.h \
		/usr/include/pango-1.0/pango/pango-fontset.h \
		/usr/include/pango-1.0/pango/pango-engine.h \
		/usr/include/pango-1.0/pango/pango-glyph.h \
		/usr/include/pango-1.0/pango/pango-enum-types.h \
		/usr/include/pango-1.0/pango/pango-features.h \
		/usr/include/pango-1.0/pango/pango-glyph-item.h \
		/usr/include/pango-1.0/pango/pango-layout.h \
		/usr/include/pango-1.0/pango/pango-tabs.h \
		/usr/include/pango-1.0/pango/pango-renderer.h \
		/usr/include/pango-1.0/pango/pango-utils.h \
		/usr/lib/x86_64-linux-gnu/gtk-2.0/include/gdkconfig.h \
		/usr/include/gtk-2.0/gdk/gdkdisplay.h \
		/usr/include/gtk-2.0/gdk/gdkevents.h \
		/usr/include/gtk-2.0/gdk/gdkcolor.h \
		/usr/include/gtk-2.0/gdk/gdkdnd.h \
		/usr/include/gtk-2.0/gdk/gdkinput.h \
		/usr/include/gtk-2.0/gdk/gdkcairo.h \
		/usr/include/gtk-2.0/gdk/gdkpixbuf.h \
		/usr/include/gtk-2.0/gdk/gdkrgb.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-features.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-transform.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-io.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h \
		/usr/include/pango-1.0/pango/pangocairo.h \
		/usr/include/gtk-2.0/gdk/gdkcursor.h \
		/usr/include/gtk-2.0/gdk/gdkdisplaymanager.h \
		/usr/include/gtk-2.0/gdk/gdkdrawable.h \
		/usr/include/gtk-2.0/gdk/gdkgc.h \
		/usr/include/gtk-2.0/gdk/gdkenumtypes.h \
		/usr/include/gtk-2.0/gdk/gdkfont.h \
		/usr/include/gtk-2.0/gdk/gdkimage.h \
		/usr/include/gtk-2.0/gdk/gdkkeys.h \
		/usr/include/gtk-2.0/gdk/gdkpango.h \
		/usr/include/gtk-2.0/gdk/gdkpixmap.h \
		/usr/include/gtk-2.0/gdk/gdkproperty.h \
		/usr/include/gtk-2.0/gdk/gdkregion.h \
		/usr/include/gtk-2.0/gdk/gdkselection.h \
		/usr/include/gtk-2.0/gdk/gdkspawn.h \
		/usr/include/gtk-2.0/gdk/gdktestutils.h \
		/usr/include/gtk-2.0/gdk/gdkwindow.h \
		/usr/include/gtk-2.0/gdk/gdkvisual.h \
		/usr/include/gtk-2.0/gtk/gtkaboutdialog.h \
		/usr/include/gtk-2.0/gtk/gtkdialog.h \
		/usr/include/gtk-2.0/gtk/gtkwindow.h \
		/usr/include/gtk-2.0/gtk/gtkaccelgroup.h \
		/usr/include/gtk-2.0/gtk/gtkenums.h \
		/usr/include/gtk-2.0/gtk/gtkbin.h \
		/usr/include/gtk-2.0/gtk/gtkcontainer.h \
		/usr/include/gtk-2.0/gtk/gtkwidget.h \
		/usr/include/gtk-2.0/gtk/gtkobject.h \
		/usr/include/gtk-2.0/gtk/gtktypeutils.h \
		/usr/include/gtk-2.0/gtk/gtktypebuiltins.h \
		/usr/include/gtk-2.0/gtk/gtkdebug.h \
		/usr/include/gtk-2.0/gtk/gtkadjustment.h \
		/usr/include/gtk-2.0/gtk/gtkstyle.h \
		/usr/include/gtk-2.0/gtk/gtksettings.h \
		/usr/include/gtk-2.0/gtk/gtkrc.h \
		/usr/include/atk-1.0/atk/atk.h \
		/usr/include/atk-1.0/atk/atkobject.h \
		/usr/include/atk-1.0/atk/atkstate.h \
		/usr/include/atk-1.0/atk/atkrelationtype.h \
		/usr/include/atk-1.0/atk/atkaction.h \
		/usr/include/atk-1.0/atk/atkcomponent.h \
		/usr/include/atk-1.0/atk/atkutil.h \
		/usr/include/atk-1.0/atk/atkdocument.h \
		/usr/include/atk-1.0/atk/atkeditabletext.h \
		/usr/include/atk-1.0/atk/atktext.h \
		/usr/include/atk-1.0/atk/atkgobjectaccessible.h \
		/usr/include/atk-1.0/atk/atkhyperlink.h \
		/usr/include/atk-1.0/atk/atkhyperlinkimpl.h \
		/usr/include/atk-1.0/atk/atkhypertext.h \
		/usr/include/atk-1.0/atk/atkimage.h \
		/usr/include/atk-1.0/atk/atknoopobject.h \
		/usr/include/atk-1.0/atk/atknoopobjectfactory.h \
		/usr/include/atk-1.0/atk/atkobjectfactory.h \
		/usr/include/atk-1.0/atk/atkplug.h \
		/usr/include/atk-1.0/atk/atkregistry.h \
		/usr/include/atk-1.0/atk/atkrelation.h \
		/usr/include/atk-1.0/atk/atkrelationset.h \
		/usr/include/atk-1.0/atk/atkselection.h \
		/usr/include/atk-1.0/atk/atksocket.h \
		/usr/include/atk-1.0/atk/atkstateset.h \
		/usr/include/atk-1.0/atk/atkstreamablecontent.h \
		/usr/include/atk-1.0/atk/atktable.h \
		/usr/include/atk-1.0/atk/atkmisc.h \
		/usr/include/atk-1.0/atk/atkvalue.h \
		/usr/include/atk-1.0/atk/atkversion.h \
		/usr/include/atk-1.0/atk/atkwindow.h \
		/usr/include/gtk-2.0/gtk/gtkaccellabel.h \
		/usr/include/gtk-2.0/gtk/gtklabel.h \
		/usr/include/gtk-2.0/gtk/gtkmisc.h \
		/usr/include/gtk-2.0/gtk/gtkmenu.h \
		/usr/include/gtk-2.0/gtk/gtkmenushell.h \
		/usr/include/gtk-2.0/gtk/gtkaccelmap.h \
		/usr/include/gtk-2.0/gtk/gtkaccessible.h \
		/usr/include/gtk-2.0/gtk/gtkaction.h \
		/usr/include/gtk-2.0/gtk/gtkactiongroup.h \
		/usr/include/gtk-2.0/gtk/gtkactivatable.h \
		/usr/include/gtk-2.0/gtk/gtkalignment.h \
		/usr/include/gtk-2.0/gtk/gtkarrow.h \
		/usr/include/gtk-2.0/gtk/gtkaspectframe.h \
		/usr/include/gtk-2.0/gtk/gtkframe.h \
		/usr/include/gtk-2.0/gtk/gtkassistant.h \
		/usr/include/gtk-2.0/gtk/gtkbbox.h \
		/usr/include/gtk-2.0/gtk/gtkbox.h \
		/usr/include/gtk-2.0/gtk/gtkbindings.h \
		/usr/include/gtk-2.0/gtk/gtkbuildable.h \
		/usr/include/gtk-2.0/gtk/gtkbuilder.h \
		/usr/include/gtk-2.0/gtk/gtkbutton.h \
		/usr/include/gtk-2.0/gtk/gtkimage.h \
		/usr/include/gtk-2.0/gtk/gtkcalendar.h \
		/usr/include/gtk-2.0/gtk/gtksignal.h \
		/usr/include/gtk-2.0/gtk/gtkmarshal.h \
		/usr/include/gtk-2.0/gtk/gtkcelleditable.h \
		/usr/include/gtk-2.0/gtk/gtkcelllayout.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderer.h \
		/usr/include/gtk-2.0/gtk/gtktreeviewcolumn.h \
		/usr/include/gtk-2.0/gtk/gtktreemodel.h \
		/usr/include/gtk-2.0/gtk/gtktreesortable.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendereraccel.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderertext.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderercombo.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererpixbuf.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererprogress.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererspin.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererspinner.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderertoggle.h \
		/usr/include/gtk-2.0/gtk/gtkcellview.h \
		/usr/include/gtk-2.0/gtk/gtkcheckbutton.h \
		/usr/include/gtk-2.0/gtk/gtktogglebutton.h \
		/usr/include/gtk-2.0/gtk/gtkcheckmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkitem.h \
		/usr/include/gtk-2.0/gtk/gtkclipboard.h \
		/usr/include/gtk-2.0/gtk/gtkselection.h \
		/usr/include/gtk-2.0/gtk/gtktextiter.h \
		/usr/include/gtk-2.0/gtk/gtktexttag.h \
		/usr/include/gtk-2.0/gtk/gtktextchild.h \
		/usr/include/gtk-2.0/gtk/gtkcolorbutton.h \
		/usr/include/gtk-2.0/gtk/gtkcolorsel.h \
		/usr/include/gtk-2.0/gtk/gtkvbox.h \
		/usr/include/gtk-2.0/gtk/gtkcolorseldialog.h \
		/usr/include/gtk-2.0/gtk/gtkcombobox.h \
		/usr/include/gtk-2.0/gtk/gtktreeview.h \
		/usr/include/gtk-2.0/gtk/gtkdnd.h \
		/usr/include/gtk-2.0/gtk/gtkentry.h \
		/usr/include/gtk-2.0/gtk/gtkeditable.h \
		/usr/include/gtk-2.0/gtk/gtkimcontext.h \
		/usr/include/gtk-2.0/gtk/gtkentrybuffer.h \
		/usr/include/gtk-2.0/gtk/gtkentrycompletion.h \
		/usr/include/gtk-2.0/gtk/gtkliststore.h \
		/usr/include/gtk-2.0/gtk/gtktreemodelfilter.h \
		/usr/include/gtk-2.0/gtk/gtkcomboboxentry.h \
		/usr/include/gtk-2.0/gtk/gtkcomboboxtext.h \
		/usr/include/gtk-2.0/gtk/gtkdrawingarea.h \
		/usr/include/gtk-2.0/gtk/gtkeventbox.h \
		/usr/include/gtk-2.0/gtk/gtkexpander.h \
		/usr/include/gtk-2.0/gtk/gtkfixed.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooser.h \
		/usr/include/gtk-2.0/gtk/gtkfilefilter.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserbutton.h \
		/usr/include/gtk-2.0/gtk/gtkhbox.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserdialog.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserwidget.h \
		/usr/include/gtk-2.0/gtk/gtkfontbutton.h \
		/usr/include/gtk-2.0/gtk/gtkfontsel.h \
		/usr/include/gtk-2.0/gtk/gtkgc.h \
		/usr/include/gtk-2.0/gtk/gtkhandlebox.h \
		/usr/include/gtk-2.0/gtk/gtkhbbox.h \
		/usr/include/gtk-2.0/gtk/gtkhpaned.h \
		/usr/include/gtk-2.0/gtk/gtkpaned.h \
		/usr/include/gtk-2.0/gtk/gtkhruler.h \
		/usr/include/gtk-2.0/gtk/gtkruler.h \
		/usr/include/gtk-2.0/gtk/gtkhscale.h \
		/usr/include/gtk-2.0/gtk/gtkscale.h \
		/usr/include/gtk-2.0/gtk/gtkrange.h \
		/usr/include/gtk-2.0/gtk/gtkhscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkhseparator.h \
		/usr/include/gtk-2.0/gtk/gtkseparator.h \
		/usr/include/gtk-2.0/gtk/gtkhsv.h \
		/usr/include/gtk-2.0/gtk/gtkiconfactory.h \
		/usr/include/gtk-2.0/gtk/gtkicontheme.h \
		/usr/include/gtk-2.0/gtk/gtkiconview.h \
		/usr/include/gtk-2.0/gtk/gtktooltip.h \
		/usr/include/gtk-2.0/gtk/gtkimagemenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkimcontextsimple.h \
		/usr/include/gtk-2.0/gtk/gtkimmulticontext.h \
		/usr/include/gtk-2.0/gtk/gtkinfobar.h \
		/usr/include/gtk-2.0/gtk/gtkinvisible.h \
		/usr/include/gtk-2.0/gtk/gtklayout.h \
		/usr/include/gtk-2.0/gtk/gtklinkbutton.h \
		/usr/include/gtk-2.0/gtk/gtkmain.h \
		/usr/include/gtk-2.0/gtk/gtkmenubar.h \
		/usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoolitem.h \
		/usr/include/gtk-2.0/gtk/gtktooltips.h \
		/usr/include/gtk-2.0/gtk/gtksizegroup.h \
		/usr/include/gtk-2.0/gtk/gtkmessagedialog.h \
		/usr/include/gtk-2.0/gtk/gtkmodules.h \
		/usr/include/gtk-2.0/gtk/gtkmountoperation.h \
		/usr/include/gtk-2.0/gtk/gtknotebook.h \
		/usr/include/gtk-2.0/gtk/gtkoffscreenwindow.h \
		/usr/include/gtk-2.0/gtk/gtkorientable.h \
		/usr/include/gtk-2.0/gtk/gtkpagesetup.h \
		/usr/include/gtk-2.0/gtk/gtkpapersize.h \
		/usr/include/gtk-2.0/gtk/gtkplug.h \
		/usr/include/gtk-2.0/gtk/gtksocket.h \
		/usr/include/gtk-2.0/gtk/gtkprintcontext.h \
		/usr/include/gtk-2.0/gtk/gtkprintoperation.h \
		/usr/include/gtk-2.0/gtk/gtkprintsettings.h \
		/usr/include/gtk-2.0/gtk/gtkprintoperationpreview.h \
		/usr/include/gtk-2.0/gtk/gtkprogressbar.h \
		/usr/include/gtk-2.0/gtk/gtkprogress.h \
		/usr/include/gtk-2.0/gtk/gtkradioaction.h \
		/usr/include/gtk-2.0/gtk/gtktoggleaction.h \
		/usr/include/gtk-2.0/gtk/gtkradiobutton.h \
		/usr/include/gtk-2.0/gtk/gtkradiomenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkradiotoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoggletoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtkrecentaction.h \
		/usr/include/gtk-2.0/gtk/gtkrecentmanager.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooser.h \
		/usr/include/gtk-2.0/gtk/gtkrecentfilter.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooserdialog.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchoosermenu.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooserwidget.h \
		/usr/include/gtk-2.0/gtk/gtkscalebutton.h \
		/usr/include/gtk-2.0/gtk/gtkscrolledwindow.h \
		/usr/include/gtk-2.0/gtk/gtkvscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkviewport.h \
		/usr/include/gtk-2.0/gtk/gtkseparatormenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkseparatortoolitem.h \
		/usr/include/gtk-2.0/gtk/gtkshow.h \
		/usr/include/gtk-2.0/gtk/gtkspinbutton.h \
		/usr/include/gtk-2.0/gtk/gtkspinner.h \
		/usr/include/gtk-2.0/gtk/gtkstatusbar.h \
		/usr/include/gtk-2.0/gtk/gtkstatusicon.h \
		/usr/include/gtk-2.0/gtk/gtkstock.h \
		/usr/include/gtk-2.0/gtk/gtktable.h \
		/usr/include/gtk-2.0/gtk/gtktearoffmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtktextbuffer.h \
		/usr/include/gtk-2.0/gtk/gtktexttagtable.h \
		/usr/include/gtk-2.0/gtk/gtktextmark.h \
		/usr/include/gtk-2.0/gtk/gtktextbufferrichtext.h \
		/usr/include/gtk-2.0/gtk/gtktextview.h \
		/usr/include/gtk-2.0/gtk/gtktoolbar.h \
		/usr/include/gtk-2.0/gtk/gtkpixmap.h \
		/usr/include/gtk-2.0/gtk/gtktoolitemgroup.h \
		/usr/include/gtk-2.0/gtk/gtktoolpalette.h \
		/usr/include/gtk-2.0/gtk/gtktoolshell.h \
		/usr/include/gtk-2.0/gtk/gtktestutils.h \
		/usr/include/gtk-2.0/gtk/gtktreednd.h \
		/usr/include/gtk-2.0/gtk/gtktreemodelsort.h \
		/usr/include/gtk-2.0/gtk/gtktreeselection.h \
		/usr/include/gtk-2.0/gtk/gtktreestore.h \
		/usr/include/gtk-2.0/gtk/gtkuimanager.h \
		/usr/include/gtk-2.0/gtk/gtkvbbox.h \
		/usr/include/gtk-2.0/gtk/gtkversion.h \
		/usr/include/gtk-2.0/gtk/gtkvolumebutton.h \
		/usr/include/gtk-2.0/gtk/gtkvpaned.h \
		/usr/include/gtk-2.0/gtk/gtkvruler.h \
		/usr/include/gtk-2.0/gtk/gtkvscale.h \
		/usr/include/gtk-2.0/gtk/gtkvseparator.h \
		/usr/include/gtk-2.0/gtk/gtktext.h \
		/usr/include/gtk-2.0/gtk/gtkoldeditable.h \
		/usr/include/gtk-2.0/gtk/gtktree.h \
		/usr/include/gtk-2.0/gtk/gtktreeitem.h \
		/usr/include/gtk-2.0/gtk/gtkclist.h \
		/usr/include/gtk-2.0/gtk/gtkcombo.h \
		/usr/include/gtk-2.0/gtk/gtkctree.h \
		/usr/include/gtk-2.0/gtk/gtkcurve.h \
		/usr/include/gtk-2.0/gtk/gtkfilesel.h \
		/usr/include/gtk-2.0/gtk/gtkgamma.h \
		/usr/include/gtk-2.0/gtk/gtkinputdialog.h \
		/usr/include/gtk-2.0/gtk/gtkitemfactory.h \
		/usr/include/gtk-2.0/gtk/gtklist.h \
		/usr/include/gtk-2.0/gtk/gtklistitem.h \
		/usr/include/gtk-2.0/gtk/gtkoptionmenu.h \
		/usr/include/gtk-2.0/gtk/gtkpreview.h \
		/usr/include/gtk-2.0/gtk/gtktipsquery.h \
		/usr/include/gtk-2.0/gdk/gdkx.h \
		/usr/include/gtk-2.0/gdk/gdkprivate.h \
		QtCefWidget.h \
		/usr/include/qt5/QtGui/QWindow \
		/usr/include/qt5/QtGui/qwindow.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QEvent \
		/usr/include/qt5/QtCore/QMargins \
		/usr/include/qt5/QtCore/QRect \
		/usr/include/qt5/QtGui/qsurface.h \
		/usr/include/qt5/QtGui/qsurfaceformat.h \
		../../cef/chromium/src/cef/include/cef_app.h \
		../../cef/chromium/src/cef/include/cef_base.h \
		../../cef/chromium/src/cef/include/internal/cef_build.h \
		../../cef/chromium/src/cef/include/internal/cef_ptr.h \
		../../cef/chromium/src/cef/include/internal/cef_types_wrappers.h \
		../../cef/chromium/src/cef/include/internal/cef_string.h \
		../../cef/chromium/src/cef/include/internal/cef_string_types.h \
		../../cef/chromium/src/cef/include/internal/cef_export.h \
		../../cef/chromium/src/cef/include/internal/cef_string_wrappers.h \
		../../cef/chromium/src/cef/include/internal/cef_string_list.h \
		../../cef/chromium/src/cef/include/internal/cef_types.h \
		../../cef/chromium/src/cef/include/internal/cef_time.h \
		../../cef/chromium/src/cef/include/internal/cef_types_win.h \
		../../cef/chromium/src/cef/include/internal/cef_types_mac.h \
		../../cef/chromium/src/cef/include/internal/cef_types_linux.h \
		../../cef/chromium/src/cef/include/internal/cef_win.h \
		../../cef/chromium/src/cef/include/internal/cef_mac.h \
		../../cef/chromium/src/cef/include/internal/cef_linux.h \
		../../cef/chromium/src/cef/include/cef_browser_process_handler.h \
		../../cef/chromium/src/cef/include/cef_command_line.h \
		../../cef/chromium/src/cef/include/cef_values.h \
		../../cef/chromium/src/cef/include/cef_render_process_handler.h \
		../../cef/chromium/src/cef/include/cef_browser.h \
		../../cef/chromium/src/cef/include/cef_frame.h \
		../../cef/chromium/src/cef/include/cef_dom.h \
		../../cef/chromium/src/cef/include/cef_request.h \
		../../cef/chromium/src/cef/include/cef_stream.h \
		../../cef/chromium/src/cef/include/cef_string_visitor.h \
		../../cef/chromium/src/cef/include/cef_process_message.h \
		../../cef/chromium/src/cef/include/cef_request_context.h \
		../../cef/chromium/src/cef/include/cef_request_context_handler.h \
		../../cef/chromium/src/cef/include/cef_cookie.h \
		../../cef/chromium/src/cef/include/cef_callback.h \
		../../cef/chromium/src/cef/include/cef_load_handler.h \
		../../cef/chromium/src/cef/include/cef_v8.h \
		../../cef/chromium/src/cef/include/cef_task.h \
		../../cef/chromium/src/cef/include/cef_resource_bundle_handler.h \
		../../cef/chromium/src/cef/include/cef_scheme.h \
		../../cef/chromium/src/cef/include/cef_response.h \
		../../cef/chromium/src/cef/include/cef_resource_handler.h \
		../../cef/chromium/src/cef/include/cef_client.h \
		../../cef/chromium/src/cef/include/cef_context_menu_handler.h \
		../../cef/chromium/src/cef/include/cef_menu_model.h \
		../../cef/chromium/src/cef/include/cef_dialog_handler.h \
		../../cef/chromium/src/cef/include/cef_display_handler.h \
		../../cef/chromium/src/cef/include/cef_download_handler.h \
		../../cef/chromium/src/cef/include/cef_download_item.h \
		../../cef/chromium/src/cef/include/cef_drag_handler.h \
		../../cef/chromium/src/cef/include/cef_drag_data.h \
		../../cef/chromium/src/cef/include/cef_focus_handler.h \
		../../cef/chromium/src/cef/include/cef_geolocation_handler.h \
		../../cef/chromium/src/cef/include/cef_jsdialog_handler.h \
		../../cef/chromium/src/cef/include/cef_keyboard_handler.h \
		../../cef/chromium/src/cef/include/cef_life_span_handler.h \
		../../cef/chromium/src/cef/include/cef_request_handler.h \
		../../cef/chromium/src/cef/include/cef_auth_callback.h \
		../../cef/chromium/src/cef/include/cef_web_plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		ui_mainwindow.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QCalendarWidget \
		/usr/include/qt5/QtWidgets/qcalendarwidget.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/QMenu \
		/usr/include/qt5/QtWidgets/qmenu.h \
		/usr/include/qt5/QtWidgets/QMenuBar \
		/usr/include/qt5/QtWidgets/qmenubar.h \
		/usr/include/qt5/QtWidgets/QStatusBar \
		/usr/include/qt5/QtWidgets/qstatusbar.h \
		/usr/include/qt5/QtWidgets/QToolBar \
		/usr/include/qt5/QtWidgets/qtoolbar.h \
		/usr/include/qt5/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

QtCefWidget.o: QtCefWidget.cpp /usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtGui/QWindow \
		/usr/include/qt5/QtGui/qwindow.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QEvent \
		/usr/include/qt5/QtCore/QMargins \
		/usr/include/qt5/QtCore/QRect \
		/usr/include/qt5/QtGui/qsurface.h \
		/usr/include/qt5/QtGui/qsurfaceformat.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/gtk-2.0/gtk/gtk.h \
		/usr/include/gtk-2.0/gdk/gdk.h \
		/usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h \
		/usr/include/glib-2.0/gio/gio.h \
		/usr/include/glib-2.0/gio/giotypes.h \
		/usr/include/glib-2.0/gio/gioenums.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/glib-2.0/gio/gaction.h \
		/usr/include/glib-2.0/gio/gactiongroup.h \
		/usr/include/glib-2.0/gio/gactiongroupexporter.h \
		/usr/include/glib-2.0/gio/gactionmap.h \
		/usr/include/glib-2.0/gio/gappinfo.h \
		/usr/include/glib-2.0/gio/gapplication.h \
		/usr/include/glib-2.0/gio/gapplicationcommandline.h \
		/usr/include/glib-2.0/gio/gasyncinitable.h \
		/usr/include/glib-2.0/gio/ginitable.h \
		/usr/include/glib-2.0/gio/gasyncresult.h \
		/usr/include/glib-2.0/gio/gbufferedinputstream.h \
		/usr/include/glib-2.0/gio/gfilterinputstream.h \
		/usr/include/glib-2.0/gio/ginputstream.h \
		/usr/include/glib-2.0/gio/gbufferedoutputstream.h \
		/usr/include/glib-2.0/gio/gfilteroutputstream.h \
		/usr/include/glib-2.0/gio/goutputstream.h \
		/usr/include/glib-2.0/gio/gbytesicon.h \
		/usr/include/glib-2.0/gio/gcancellable.h \
		/usr/include/glib-2.0/gio/gcharsetconverter.h \
		/usr/include/glib-2.0/gio/gconverter.h \
		/usr/include/glib-2.0/gio/gcontenttype.h \
		/usr/include/glib-2.0/gio/gconverterinputstream.h \
		/usr/include/glib-2.0/gio/gconverteroutputstream.h \
		/usr/include/glib-2.0/gio/gcredentials.h \
		/usr/include/glib-2.0/gio/gdatainputstream.h \
		/usr/include/glib-2.0/gio/gdataoutputstream.h \
		/usr/include/glib-2.0/gio/gdbusaddress.h \
		/usr/include/glib-2.0/gio/gdbusauthobserver.h \
		/usr/include/glib-2.0/gio/gdbusconnection.h \
		/usr/include/glib-2.0/gio/gdbuserror.h \
		/usr/include/glib-2.0/gio/gdbusintrospection.h \
		/usr/include/glib-2.0/gio/gdbusmessage.h \
		/usr/include/glib-2.0/gio/gdbusmethodinvocation.h \
		/usr/include/glib-2.0/gio/gdbusnameowning.h \
		/usr/include/glib-2.0/gio/gdbusnamewatching.h \
		/usr/include/glib-2.0/gio/gdbusproxy.h \
		/usr/include/glib-2.0/gio/gdbusserver.h \
		/usr/include/glib-2.0/gio/gdbusutils.h \
		/usr/include/glib-2.0/gio/gdrive.h \
		/usr/include/glib-2.0/gio/gemblemedicon.h \
		/usr/include/glib-2.0/gio/gicon.h \
		/usr/include/glib-2.0/gio/gemblem.h \
		/usr/include/glib-2.0/gio/gfileattribute.h \
		/usr/include/glib-2.0/gio/gfileenumerator.h \
		/usr/include/glib-2.0/gio/gfile.h \
		/usr/include/glib-2.0/gio/gfileicon.h \
		/usr/include/glib-2.0/gio/gfileinfo.h \
		/usr/include/glib-2.0/gio/gfileinputstream.h \
		/usr/include/glib-2.0/gio/gfileiostream.h \
		/usr/include/glib-2.0/gio/giostream.h \
		/usr/include/glib-2.0/gio/gioerror.h \
		/usr/include/glib-2.0/gio/gfilemonitor.h \
		/usr/include/glib-2.0/gio/gfilenamecompleter.h \
		/usr/include/glib-2.0/gio/gfileoutputstream.h \
		/usr/include/glib-2.0/gio/ginetaddress.h \
		/usr/include/glib-2.0/gio/ginetaddressmask.h \
		/usr/include/glib-2.0/gio/ginetsocketaddress.h \
		/usr/include/glib-2.0/gio/gsocketaddress.h \
		/usr/include/glib-2.0/gio/gioenumtypes.h \
		/usr/include/glib-2.0/gio/giomodule.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/glib-2.0/gio/gioscheduler.h \
		/usr/include/glib-2.0/gio/gloadableicon.h \
		/usr/include/glib-2.0/gio/gmemoryinputstream.h \
		/usr/include/glib-2.0/gio/gmemoryoutputstream.h \
		/usr/include/glib-2.0/gio/gmount.h \
		/usr/include/glib-2.0/gio/gmountoperation.h \
		/usr/include/glib-2.0/gio/gnativevolumemonitor.h \
		/usr/include/glib-2.0/gio/gvolumemonitor.h \
		/usr/include/glib-2.0/gio/gnetworkaddress.h \
		/usr/include/glib-2.0/gio/gnetworkmonitor.h \
		/usr/include/glib-2.0/gio/gnetworkservice.h \
		/usr/include/glib-2.0/gio/gpermission.h \
		/usr/include/glib-2.0/gio/gpollableinputstream.h \
		/usr/include/glib-2.0/gio/gpollableoutputstream.h \
		/usr/include/glib-2.0/gio/gpollableutils.h \
		/usr/include/glib-2.0/gio/gpropertyaction.h \
		/usr/include/glib-2.0/gio/gproxy.h \
		/usr/include/glib-2.0/gio/gproxyaddress.h \
		/usr/include/glib-2.0/gio/gproxyaddressenumerator.h \
		/usr/include/glib-2.0/gio/gsocketaddressenumerator.h \
		/usr/include/glib-2.0/gio/gproxyresolver.h \
		/usr/include/glib-2.0/gio/gresolver.h \
		/usr/include/glib-2.0/gio/gresource.h \
		/usr/include/glib-2.0/gio/gseekable.h \
		/usr/include/glib-2.0/gio/gsettingsschema.h \
		/usr/include/glib-2.0/gio/gsettings.h \
		/usr/include/glib-2.0/gio/gsimpleaction.h \
		/usr/include/glib-2.0/gio/gsimpleactiongroup.h \
		/usr/include/glib-2.0/gio/gsimpleasyncresult.h \
		/usr/include/glib-2.0/gio/gsimplepermission.h \
		/usr/include/glib-2.0/gio/gsocketclient.h \
		/usr/include/glib-2.0/gio/gsocketconnectable.h \
		/usr/include/glib-2.0/gio/gsocketconnection.h \
		/usr/include/glib-2.0/gio/gsocket.h \
		/usr/include/glib-2.0/gio/gsocketcontrolmessage.h \
		/usr/include/glib-2.0/gio/gsocketlistener.h \
		/usr/include/glib-2.0/gio/gsocketservice.h \
		/usr/include/glib-2.0/gio/gsrvtarget.h \
		/usr/include/glib-2.0/gio/gsimpleproxyresolver.h \
		/usr/include/glib-2.0/gio/gtask.h \
		/usr/include/glib-2.0/gio/gsubprocess.h \
		/usr/include/glib-2.0/gio/gsubprocesslauncher.h \
		/usr/include/glib-2.0/gio/gtcpconnection.h \
		/usr/include/glib-2.0/gio/gtcpwrapperconnection.h \
		/usr/include/glib-2.0/gio/gtestdbus.h \
		/usr/include/glib-2.0/gio/gthemedicon.h \
		/usr/include/glib-2.0/gio/gthreadedsocketservice.h \
		/usr/include/glib-2.0/gio/gtlsbackend.h \
		/usr/include/glib-2.0/gio/gtlscertificate.h \
		/usr/include/glib-2.0/gio/gtlsclientconnection.h \
		/usr/include/glib-2.0/gio/gtlsconnection.h \
		/usr/include/glib-2.0/gio/gtlsdatabase.h \
		/usr/include/glib-2.0/gio/gtlsfiledatabase.h \
		/usr/include/glib-2.0/gio/gtlsinteraction.h \
		/usr/include/glib-2.0/gio/gtlsserverconnection.h \
		/usr/include/glib-2.0/gio/gtlspassword.h \
		/usr/include/glib-2.0/gio/gvfs.h \
		/usr/include/glib-2.0/gio/gvolume.h \
		/usr/include/glib-2.0/gio/gzlibcompressor.h \
		/usr/include/glib-2.0/gio/gzlibdecompressor.h \
		/usr/include/glib-2.0/gio/gdbusinterface.h \
		/usr/include/glib-2.0/gio/gdbusinterfaceskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobject.h \
		/usr/include/glib-2.0/gio/gdbusobjectskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobjectproxy.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanager.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerclient.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerserver.h \
		/usr/include/glib-2.0/gio/gdbusactiongroup.h \
		/usr/include/glib-2.0/gio/gremoteactiongroup.h \
		/usr/include/glib-2.0/gio/gmenumodel.h \
		/usr/include/glib-2.0/gio/gmenu.h \
		/usr/include/glib-2.0/gio/gmenuexporter.h \
		/usr/include/glib-2.0/gio/gdbusmenumodel.h \
		/usr/include/glib-2.0/gio/gnotification.h \
		/usr/include/gtk-2.0/gdk/gdkscreen.h \
		/usr/include/cairo/cairo.h \
		/usr/include/cairo/cairo-version.h \
		/usr/include/cairo/cairo-features.h \
		/usr/include/cairo/cairo-deprecated.h \
		/usr/include/gtk-2.0/gdk/gdktypes.h \
		/usr/include/pango-1.0/pango/pango.h \
		/usr/include/pango-1.0/pango/pango-attributes.h \
		/usr/include/pango-1.0/pango/pango-font.h \
		/usr/include/pango-1.0/pango/pango-coverage.h \
		/usr/include/pango-1.0/pango/pango-types.h \
		/usr/include/pango-1.0/pango/pango-gravity.h \
		/usr/include/pango-1.0/pango/pango-matrix.h \
		/usr/include/pango-1.0/pango/pango-script.h \
		/usr/include/pango-1.0/pango/pango-language.h \
		/usr/include/pango-1.0/pango/pango-bidi-type.h \
		/usr/include/pango-1.0/pango/pango-break.h \
		/usr/include/pango-1.0/pango/pango-item.h \
		/usr/include/pango-1.0/pango/pango-context.h \
		/usr/include/pango-1.0/pango/pango-fontmap.h \
		/usr/include/pango-1.0/pango/pango-fontset.h \
		/usr/include/pango-1.0/pango/pango-engine.h \
		/usr/include/pango-1.0/pango/pango-glyph.h \
		/usr/include/pango-1.0/pango/pango-enum-types.h \
		/usr/include/pango-1.0/pango/pango-features.h \
		/usr/include/pango-1.0/pango/pango-glyph-item.h \
		/usr/include/pango-1.0/pango/pango-layout.h \
		/usr/include/pango-1.0/pango/pango-tabs.h \
		/usr/include/pango-1.0/pango/pango-renderer.h \
		/usr/include/pango-1.0/pango/pango-utils.h \
		/usr/lib/x86_64-linux-gnu/gtk-2.0/include/gdkconfig.h \
		/usr/include/gtk-2.0/gdk/gdkdisplay.h \
		/usr/include/gtk-2.0/gdk/gdkevents.h \
		/usr/include/gtk-2.0/gdk/gdkcolor.h \
		/usr/include/gtk-2.0/gdk/gdkdnd.h \
		/usr/include/gtk-2.0/gdk/gdkinput.h \
		/usr/include/gtk-2.0/gdk/gdkcairo.h \
		/usr/include/gtk-2.0/gdk/gdkpixbuf.h \
		/usr/include/gtk-2.0/gdk/gdkrgb.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-features.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-transform.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-io.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h \
		/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h \
		/usr/include/pango-1.0/pango/pangocairo.h \
		/usr/include/gtk-2.0/gdk/gdkcursor.h \
		/usr/include/gtk-2.0/gdk/gdkdisplaymanager.h \
		/usr/include/gtk-2.0/gdk/gdkdrawable.h \
		/usr/include/gtk-2.0/gdk/gdkgc.h \
		/usr/include/gtk-2.0/gdk/gdkenumtypes.h \
		/usr/include/gtk-2.0/gdk/gdkfont.h \
		/usr/include/gtk-2.0/gdk/gdkimage.h \
		/usr/include/gtk-2.0/gdk/gdkkeys.h \
		/usr/include/gtk-2.0/gdk/gdkpango.h \
		/usr/include/gtk-2.0/gdk/gdkpixmap.h \
		/usr/include/gtk-2.0/gdk/gdkproperty.h \
		/usr/include/gtk-2.0/gdk/gdkregion.h \
		/usr/include/gtk-2.0/gdk/gdkselection.h \
		/usr/include/gtk-2.0/gdk/gdkspawn.h \
		/usr/include/gtk-2.0/gdk/gdktestutils.h \
		/usr/include/gtk-2.0/gdk/gdkwindow.h \
		/usr/include/gtk-2.0/gdk/gdkvisual.h \
		/usr/include/gtk-2.0/gtk/gtkaboutdialog.h \
		/usr/include/gtk-2.0/gtk/gtkdialog.h \
		/usr/include/gtk-2.0/gtk/gtkwindow.h \
		/usr/include/gtk-2.0/gtk/gtkaccelgroup.h \
		/usr/include/gtk-2.0/gtk/gtkenums.h \
		/usr/include/gtk-2.0/gtk/gtkbin.h \
		/usr/include/gtk-2.0/gtk/gtkcontainer.h \
		/usr/include/gtk-2.0/gtk/gtkwidget.h \
		/usr/include/gtk-2.0/gtk/gtkobject.h \
		/usr/include/gtk-2.0/gtk/gtktypeutils.h \
		/usr/include/gtk-2.0/gtk/gtktypebuiltins.h \
		/usr/include/gtk-2.0/gtk/gtkdebug.h \
		/usr/include/gtk-2.0/gtk/gtkadjustment.h \
		/usr/include/gtk-2.0/gtk/gtkstyle.h \
		/usr/include/gtk-2.0/gtk/gtksettings.h \
		/usr/include/gtk-2.0/gtk/gtkrc.h \
		/usr/include/atk-1.0/atk/atk.h \
		/usr/include/atk-1.0/atk/atkobject.h \
		/usr/include/atk-1.0/atk/atkstate.h \
		/usr/include/atk-1.0/atk/atkrelationtype.h \
		/usr/include/atk-1.0/atk/atkaction.h \
		/usr/include/atk-1.0/atk/atkcomponent.h \
		/usr/include/atk-1.0/atk/atkutil.h \
		/usr/include/atk-1.0/atk/atkdocument.h \
		/usr/include/atk-1.0/atk/atkeditabletext.h \
		/usr/include/atk-1.0/atk/atktext.h \
		/usr/include/atk-1.0/atk/atkgobjectaccessible.h \
		/usr/include/atk-1.0/atk/atkhyperlink.h \
		/usr/include/atk-1.0/atk/atkhyperlinkimpl.h \
		/usr/include/atk-1.0/atk/atkhypertext.h \
		/usr/include/atk-1.0/atk/atkimage.h \
		/usr/include/atk-1.0/atk/atknoopobject.h \
		/usr/include/atk-1.0/atk/atknoopobjectfactory.h \
		/usr/include/atk-1.0/atk/atkobjectfactory.h \
		/usr/include/atk-1.0/atk/atkplug.h \
		/usr/include/atk-1.0/atk/atkregistry.h \
		/usr/include/atk-1.0/atk/atkrelation.h \
		/usr/include/atk-1.0/atk/atkrelationset.h \
		/usr/include/atk-1.0/atk/atkselection.h \
		/usr/include/atk-1.0/atk/atksocket.h \
		/usr/include/atk-1.0/atk/atkstateset.h \
		/usr/include/atk-1.0/atk/atkstreamablecontent.h \
		/usr/include/atk-1.0/atk/atktable.h \
		/usr/include/atk-1.0/atk/atkmisc.h \
		/usr/include/atk-1.0/atk/atkvalue.h \
		/usr/include/atk-1.0/atk/atkversion.h \
		/usr/include/atk-1.0/atk/atkwindow.h \
		/usr/include/gtk-2.0/gtk/gtkaccellabel.h \
		/usr/include/gtk-2.0/gtk/gtklabel.h \
		/usr/include/gtk-2.0/gtk/gtkmisc.h \
		/usr/include/gtk-2.0/gtk/gtkmenu.h \
		/usr/include/gtk-2.0/gtk/gtkmenushell.h \
		/usr/include/gtk-2.0/gtk/gtkaccelmap.h \
		/usr/include/gtk-2.0/gtk/gtkaccessible.h \
		/usr/include/gtk-2.0/gtk/gtkaction.h \
		/usr/include/gtk-2.0/gtk/gtkactiongroup.h \
		/usr/include/gtk-2.0/gtk/gtkactivatable.h \
		/usr/include/gtk-2.0/gtk/gtkalignment.h \
		/usr/include/gtk-2.0/gtk/gtkarrow.h \
		/usr/include/gtk-2.0/gtk/gtkaspectframe.h \
		/usr/include/gtk-2.0/gtk/gtkframe.h \
		/usr/include/gtk-2.0/gtk/gtkassistant.h \
		/usr/include/gtk-2.0/gtk/gtkbbox.h \
		/usr/include/gtk-2.0/gtk/gtkbox.h \
		/usr/include/gtk-2.0/gtk/gtkbindings.h \
		/usr/include/gtk-2.0/gtk/gtkbuildable.h \
		/usr/include/gtk-2.0/gtk/gtkbuilder.h \
		/usr/include/gtk-2.0/gtk/gtkbutton.h \
		/usr/include/gtk-2.0/gtk/gtkimage.h \
		/usr/include/gtk-2.0/gtk/gtkcalendar.h \
		/usr/include/gtk-2.0/gtk/gtksignal.h \
		/usr/include/gtk-2.0/gtk/gtkmarshal.h \
		/usr/include/gtk-2.0/gtk/gtkcelleditable.h \
		/usr/include/gtk-2.0/gtk/gtkcelllayout.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderer.h \
		/usr/include/gtk-2.0/gtk/gtktreeviewcolumn.h \
		/usr/include/gtk-2.0/gtk/gtktreemodel.h \
		/usr/include/gtk-2.0/gtk/gtktreesortable.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendereraccel.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderertext.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderercombo.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererpixbuf.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererprogress.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererspin.h \
		/usr/include/gtk-2.0/gtk/gtkcellrendererspinner.h \
		/usr/include/gtk-2.0/gtk/gtkcellrenderertoggle.h \
		/usr/include/gtk-2.0/gtk/gtkcellview.h \
		/usr/include/gtk-2.0/gtk/gtkcheckbutton.h \
		/usr/include/gtk-2.0/gtk/gtktogglebutton.h \
		/usr/include/gtk-2.0/gtk/gtkcheckmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkitem.h \
		/usr/include/gtk-2.0/gtk/gtkclipboard.h \
		/usr/include/gtk-2.0/gtk/gtkselection.h \
		/usr/include/gtk-2.0/gtk/gtktextiter.h \
		/usr/include/gtk-2.0/gtk/gtktexttag.h \
		/usr/include/gtk-2.0/gtk/gtktextchild.h \
		/usr/include/gtk-2.0/gtk/gtkcolorbutton.h \
		/usr/include/gtk-2.0/gtk/gtkcolorsel.h \
		/usr/include/gtk-2.0/gtk/gtkvbox.h \
		/usr/include/gtk-2.0/gtk/gtkcolorseldialog.h \
		/usr/include/gtk-2.0/gtk/gtkcombobox.h \
		/usr/include/gtk-2.0/gtk/gtktreeview.h \
		/usr/include/gtk-2.0/gtk/gtkdnd.h \
		/usr/include/gtk-2.0/gtk/gtkentry.h \
		/usr/include/gtk-2.0/gtk/gtkeditable.h \
		/usr/include/gtk-2.0/gtk/gtkimcontext.h \
		/usr/include/gtk-2.0/gtk/gtkentrybuffer.h \
		/usr/include/gtk-2.0/gtk/gtkentrycompletion.h \
		/usr/include/gtk-2.0/gtk/gtkliststore.h \
		/usr/include/gtk-2.0/gtk/gtktreemodelfilter.h \
		/usr/include/gtk-2.0/gtk/gtkcomboboxentry.h \
		/usr/include/gtk-2.0/gtk/gtkcomboboxtext.h \
		/usr/include/gtk-2.0/gtk/gtkdrawingarea.h \
		/usr/include/gtk-2.0/gtk/gtkeventbox.h \
		/usr/include/gtk-2.0/gtk/gtkexpander.h \
		/usr/include/gtk-2.0/gtk/gtkfixed.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooser.h \
		/usr/include/gtk-2.0/gtk/gtkfilefilter.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserbutton.h \
		/usr/include/gtk-2.0/gtk/gtkhbox.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserdialog.h \
		/usr/include/gtk-2.0/gtk/gtkfilechooserwidget.h \
		/usr/include/gtk-2.0/gtk/gtkfontbutton.h \
		/usr/include/gtk-2.0/gtk/gtkfontsel.h \
		/usr/include/gtk-2.0/gtk/gtkgc.h \
		/usr/include/gtk-2.0/gtk/gtkhandlebox.h \
		/usr/include/gtk-2.0/gtk/gtkhbbox.h \
		/usr/include/gtk-2.0/gtk/gtkhpaned.h \
		/usr/include/gtk-2.0/gtk/gtkpaned.h \
		/usr/include/gtk-2.0/gtk/gtkhruler.h \
		/usr/include/gtk-2.0/gtk/gtkruler.h \
		/usr/include/gtk-2.0/gtk/gtkhscale.h \
		/usr/include/gtk-2.0/gtk/gtkscale.h \
		/usr/include/gtk-2.0/gtk/gtkrange.h \
		/usr/include/gtk-2.0/gtk/gtkhscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkhseparator.h \
		/usr/include/gtk-2.0/gtk/gtkseparator.h \
		/usr/include/gtk-2.0/gtk/gtkhsv.h \
		/usr/include/gtk-2.0/gtk/gtkiconfactory.h \
		/usr/include/gtk-2.0/gtk/gtkicontheme.h \
		/usr/include/gtk-2.0/gtk/gtkiconview.h \
		/usr/include/gtk-2.0/gtk/gtktooltip.h \
		/usr/include/gtk-2.0/gtk/gtkimagemenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkimcontextsimple.h \
		/usr/include/gtk-2.0/gtk/gtkimmulticontext.h \
		/usr/include/gtk-2.0/gtk/gtkinfobar.h \
		/usr/include/gtk-2.0/gtk/gtkinvisible.h \
		/usr/include/gtk-2.0/gtk/gtklayout.h \
		/usr/include/gtk-2.0/gtk/gtklinkbutton.h \
		/usr/include/gtk-2.0/gtk/gtkmain.h \
		/usr/include/gtk-2.0/gtk/gtkmenubar.h \
		/usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoolitem.h \
		/usr/include/gtk-2.0/gtk/gtktooltips.h \
		/usr/include/gtk-2.0/gtk/gtksizegroup.h \
		/usr/include/gtk-2.0/gtk/gtkmessagedialog.h \
		/usr/include/gtk-2.0/gtk/gtkmodules.h \
		/usr/include/gtk-2.0/gtk/gtkmountoperation.h \
		/usr/include/gtk-2.0/gtk/gtknotebook.h \
		/usr/include/gtk-2.0/gtk/gtkoffscreenwindow.h \
		/usr/include/gtk-2.0/gtk/gtkorientable.h \
		/usr/include/gtk-2.0/gtk/gtkpagesetup.h \
		/usr/include/gtk-2.0/gtk/gtkpapersize.h \
		/usr/include/gtk-2.0/gtk/gtkplug.h \
		/usr/include/gtk-2.0/gtk/gtksocket.h \
		/usr/include/gtk-2.0/gtk/gtkprintcontext.h \
		/usr/include/gtk-2.0/gtk/gtkprintoperation.h \
		/usr/include/gtk-2.0/gtk/gtkprintsettings.h \
		/usr/include/gtk-2.0/gtk/gtkprintoperationpreview.h \
		/usr/include/gtk-2.0/gtk/gtkprogressbar.h \
		/usr/include/gtk-2.0/gtk/gtkprogress.h \
		/usr/include/gtk-2.0/gtk/gtkradioaction.h \
		/usr/include/gtk-2.0/gtk/gtktoggleaction.h \
		/usr/include/gtk-2.0/gtk/gtkradiobutton.h \
		/usr/include/gtk-2.0/gtk/gtkradiomenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkradiotoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtktoggletoolbutton.h \
		/usr/include/gtk-2.0/gtk/gtkrecentaction.h \
		/usr/include/gtk-2.0/gtk/gtkrecentmanager.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooser.h \
		/usr/include/gtk-2.0/gtk/gtkrecentfilter.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooserdialog.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchoosermenu.h \
		/usr/include/gtk-2.0/gtk/gtkrecentchooserwidget.h \
		/usr/include/gtk-2.0/gtk/gtkscalebutton.h \
		/usr/include/gtk-2.0/gtk/gtkscrolledwindow.h \
		/usr/include/gtk-2.0/gtk/gtkvscrollbar.h \
		/usr/include/gtk-2.0/gtk/gtkviewport.h \
		/usr/include/gtk-2.0/gtk/gtkseparatormenuitem.h \
		/usr/include/gtk-2.0/gtk/gtkseparatortoolitem.h \
		/usr/include/gtk-2.0/gtk/gtkshow.h \
		/usr/include/gtk-2.0/gtk/gtkspinbutton.h \
		/usr/include/gtk-2.0/gtk/gtkspinner.h \
		/usr/include/gtk-2.0/gtk/gtkstatusbar.h \
		/usr/include/gtk-2.0/gtk/gtkstatusicon.h \
		/usr/include/gtk-2.0/gtk/gtkstock.h \
		/usr/include/gtk-2.0/gtk/gtktable.h \
		/usr/include/gtk-2.0/gtk/gtktearoffmenuitem.h \
		/usr/include/gtk-2.0/gtk/gtktextbuffer.h \
		/usr/include/gtk-2.0/gtk/gtktexttagtable.h \
		/usr/include/gtk-2.0/gtk/gtktextmark.h \
		/usr/include/gtk-2.0/gtk/gtktextbufferrichtext.h \
		/usr/include/gtk-2.0/gtk/gtktextview.h \
		/usr/include/gtk-2.0/gtk/gtktoolbar.h \
		/usr/include/gtk-2.0/gtk/gtkpixmap.h \
		/usr/include/gtk-2.0/gtk/gtktoolitemgroup.h \
		/usr/include/gtk-2.0/gtk/gtktoolpalette.h \
		/usr/include/gtk-2.0/gtk/gtktoolshell.h \
		/usr/include/gtk-2.0/gtk/gtktestutils.h \
		/usr/include/gtk-2.0/gtk/gtktreednd.h \
		/usr/include/gtk-2.0/gtk/gtktreemodelsort.h \
		/usr/include/gtk-2.0/gtk/gtktreeselection.h \
		/usr/include/gtk-2.0/gtk/gtktreestore.h \
		/usr/include/gtk-2.0/gtk/gtkuimanager.h \
		/usr/include/gtk-2.0/gtk/gtkvbbox.h \
		/usr/include/gtk-2.0/gtk/gtkversion.h \
		/usr/include/gtk-2.0/gtk/gtkvolumebutton.h \
		/usr/include/gtk-2.0/gtk/gtkvpaned.h \
		/usr/include/gtk-2.0/gtk/gtkvruler.h \
		/usr/include/gtk-2.0/gtk/gtkvscale.h \
		/usr/include/gtk-2.0/gtk/gtkvseparator.h \
		/usr/include/gtk-2.0/gtk/gtktext.h \
		/usr/include/gtk-2.0/gtk/gtkoldeditable.h \
		/usr/include/gtk-2.0/gtk/gtktree.h \
		/usr/include/gtk-2.0/gtk/gtktreeitem.h \
		/usr/include/gtk-2.0/gtk/gtkclist.h \
		/usr/include/gtk-2.0/gtk/gtkcombo.h \
		/usr/include/gtk-2.0/gtk/gtkctree.h \
		/usr/include/gtk-2.0/gtk/gtkcurve.h \
		/usr/include/gtk-2.0/gtk/gtkfilesel.h \
		/usr/include/gtk-2.0/gtk/gtkgamma.h \
		/usr/include/gtk-2.0/gtk/gtkinputdialog.h \
		/usr/include/gtk-2.0/gtk/gtkitemfactory.h \
		/usr/include/gtk-2.0/gtk/gtklist.h \
		/usr/include/gtk-2.0/gtk/gtklistitem.h \
		/usr/include/gtk-2.0/gtk/gtkoptionmenu.h \
		/usr/include/gtk-2.0/gtk/gtkpreview.h \
		/usr/include/gtk-2.0/gtk/gtktipsquery.h \
		/usr/include/gtk-2.0/gdk/gdkx.h \
		/usr/include/gtk-2.0/gdk/gdkprivate.h \
		QtCefWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtCefWidget.o QtCefWidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

